name: Build shapez CE for macOS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Yarn
      run: npm install -g yarn@1.22.22

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install FFmpeg
      run: brew install ffmpeg

    - name: Install dependencies (root)
      run: yarn

    - name: Install dependencies (electron)
      working-directory: electron
      run: yarn

    - name: Package for macOS
      run: yarn package-darwin-arm64

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: shapez-macos-arm64
        path: build_output/standalone/shapez-*
        retention-days: 7
